AI_TOPICS = [
    "machine-learning",
    "deep-learning",
    "artificial-intelligence",
    "neural-network",
    "natural-language-processing",
    "computer-vision",
    "reinforcement-learning",
    "generative-ai",
    "large-language-model",
    "transformer",
    "diffusion-model",
    "pytorch",
    "tensorflow",
    "llm",
    "gpt",
    "stable-diffusion",
    "langchain",
    "rag",
    "fine-tuning",
    "mlops",
]

AI_KEYWORDS = [
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "neural network",
    "nlp",
    "llm",
    "gpt",
    "transformer",
    "diffusion",
    "reinforcement learning",
]

AI_SEARCH_QUERIES = [
    "topic:machine-learning stars:>1000",
    "topic:deep-learning stars:>500",
    "topic:artificial-intelligence stars:>500",
    "topic:natural-language-processing stars:>500",
    "topic:computer-vision stars:>500",
    "topic:large-language-model stars:>100",
    "topic:generative-ai stars:>100",
    "topic:transformer stars:>500",
    "topic:pytorch stars:>1000",
    "topic:tensorflow stars:>1000",
    "topic:llm stars:>100",
    "topic:diffusion-model stars:>100",
    "topic:reinforcement-learning stars:>500",
    "topic:langchain stars:>100",
]
